redhat-developer/intellij-knative

src/main/java/com/redhat/devtools/intellij/knative/Constants.java
src/main/java/com/redhat/devtools/intellij/knative/WindowToolFactory.java
src/main/java/com/redhat/devtools/intellij/knative/actions/KnAction.java
src/main/java/com/redhat/devtools/intellij/knative/actions/OpenInEditorAction.java
src/main/java/com/redhat/devtools/intellij/knative/kn/Kn.java
src/main/java/com/redhat/devtools/intellij/knative/kn/KnCli.java
src/main/java/com/redhat/devtools/intellij/knative/listener/TreeDoubleClickListener.java
src/main/java/com/redhat/devtools/intellij/knative/utils/EditorHelper.java
src/main/java/com/redhat/devtools/intellij/knative/utils/KnHelper.java
src/main/resources/META-INF/plugin.xml

it resolves #3 and #4
It allows to open both components `service` and `revision` as read-only as in vscode.
I also added the double click as in tekton.
EDIT: I missed the edit action in vscode, so basically they are first opened as read-only and if the user wants to edit them he needs to click on the edit action that open a new editor tab. Not sure if we want to copy vscode or we want to open the editor in edit mode directly. Ideas? We can also discuss it in #6

add open in editor action for service (#3)

---

src/main/java/com/redhat/devtools/intellij/knative/WindowToolFactory.java
src/main/java/com/redhat/devtools/intellij/knative/kn/DeserializerUtil.java
src/main/java/com/redhat/devtools/intellij/knative/kn/KnConstants.java
src/main/java/com/redhat/devtools/intellij/knative/kn/Revision.java
src/main/java/com/redhat/devtools/intellij/knative/kn/RevisionDeserializer.java
src/main/java/com/redhat/devtools/intellij/knative/tree/KnNodeComparator.java
src/main/java/com/redhat/devtools/intellij/knative/tree/KnRevisionDescriptor.java
src/main/java/com/redhat/devtools/intellij/knative/tree/KnServiceDescriptor.java
src/main/java/com/redhat/devtools/intellij/knative/utils/TreeHelper.java

This PR adds comparator for knative tree. 
It is sorting revisions nodes based on their `serving.knative.dev/configurationGeneration` label value.
Also highlight revisions which doesn't has traffic. 
And fix tag rendering, add space between labels.
Demo:
Fix: #12

Sort revisions based on their generation

---

src/main/java/com/redhat/devtools/intellij/knative/actions/RefreshAction.java
src/main/resources/META-INF/plugin.xml

This PR just common keybindings to `Delete` and `Refresh` actions.
Fix: #29 
To add custom keybinding we may use:
```xml
<action class="com.redhat.devtools.intellij.knative.actions.OpenInEditorAction" text="Open in Editor">
<keyboard-shortcut first-keystroke="meta g" keymap="Mac OS X 10.5+"/>
<action>
```
By default IJ allows to edit keybinding for any action in preferences:
Depends on https://github.com/redhat-developer/intellij-common/pull/50

Add keybinding to Refresh and Delete action

---

build.gradle
src/main/resources/META-INF/plugin.xml

New IJ k8s release allows to switch namespace/project :rocket:

chore: add dependency to kubernetes plugin (#44)

---

build.gradle
src/main/java/com/redhat/devtools/intellij/knative/utils/KnHelper.java
src/test/java/com/redhat/devtools/intellij/knative/utils/KnHelperTest.java

it resolves #31 
This PR uses the new IJ-common library 1.1.0. 
Now you can also edit labels/annotations for an existing resource from the editor. This is needed to change a public knative service to a private one by adding `networking.knative.dev/visibility=cluster-local` as label

feat: optimize update action with new common version (#31)

---

src/main/java/com/redhat/devtools/intellij/knative/utils/EditorHelper.java

Simple fix for ClassCastException, which happened when root tree item has double click.

fix: ClassCastException when double click on root node

---

src/main/java/com/redhat/devtools/intellij/knative/actions/func/UndeployAction.java
src/main/java/com/redhat/devtools/intellij/knative/utils/WatchHandler.java
src/main/java/com/redhat/devtools/intellij/knative/watch/FunctionWatcher.java

it resolves #98 
Now it prints two notifications. First when undeploy starts and then when it completes

feat: show notification when undeploy action is complete (#98)

---

src/main/resources/func.json
src/main/resources/kn.json

Just found out the detection in PATH didn't work correctly because of wrong regexes rules

fix: update regexes to discover clis in PATH (#112)

---

src/main/java/com/redhat/devtools/intellij/knative/actions/func/InvokeAction.java
src/main/java/com/redhat/devtools/intellij/knative/kn/Kn.java
src/main/java/com/redhat/devtools/intellij/knative/kn/KnCli.java
src/main/java/com/redhat/devtools/intellij/knative/ui/invokeFunc/InvokeDialog.java
src/main/java/com/redhat/devtools/intellij/knative/utils/MimeTypes.java
src/main/java/com/redhat/devtools/intellij/knative/utils/model/InvokeModel.java
src/main/resources/META-INF/plugin.xml
src/main/resources/func.json

it resolves #96 
An example below. Few things to be mentioned.
1) If you open an only local/only remote function you won't see the instances options at the top.
2) The content-type textboxes is auto-filled based on the file picked by the user (e.g a file .jpg will have the image/jpeg mime type automatically selected)
3) The func cli claims to get values from env variables for their args. I only check those related to source/format/type/content-type/id. I skipped the others as i don't think it makes sense from an IDE perspective :thinking: 
cc @sudhirverma @mohitsuman

feat: add invoke action

---

build.gradle
src/main/java/com/redhat/devtools/intellij/knative/Constants.java
src/main/java/com/redhat/devtools/intellij/knative/actions/func/BuildAction.java
src/main/java/com/redhat/devtools/intellij/knative/actions/func/DeployAction.java
src/main/java/com/redhat/devtools/intellij/knative/actions/toolbar/ShowBuildHistoryAction.java
src/main/java/com/redhat/devtools/intellij/knative/kn/Function.java
src/main/java/com/redhat/devtools/intellij/knative/kn/Kn.java
src/main/java/com/redhat/devtools/intellij/knative/kn/KnCli.java
src/main/java/com/redhat/devtools/intellij/knative/ui/buildFunc/BuildFuncExec.java
src/main/java/com/redhat/devtools/intellij/knative/ui/buildFunc/BuildFuncHandler.java
src/main/java/com/redhat/devtools/intellij/knative/ui/buildFunc/BuildFuncPanel.java
src/main/java/com/redhat/devtools/intellij/knative/ui/buildFunc/BuildFuncWindowToolFactory.java
src/main/resources/META-INF/plugin.xml
src/test/java/com/redhat/devtools/intellij/knative/BaseTest.java
src/test/java/com/redhat/devtools/intellij/knative/actions/ActionTest.java
src/test/java/com/redhat/devtools/intellij/knative/actions/BuildActionTest.java
src/test/java/com/redhat/devtools/intellij/knative/actions/DeleteActionTest.java
src/test/java/com/redhat/devtools/intellij/knative/actions/DeployActionTest.java
src/test/java/com/redhat/devtools/intellij/knative/kn/KnCliTest.java

This is the stuff i'm working on. Still not completed but it's a good point to start a discussion. One of the biggest problem we have in both knative plugins are the multiple terminal tabs that gets opened when several actions are executed. This is the proposal for IJ for function builds. A custom tool window which shows the state of the builds with all logs on the terminal.
If you re-run multiple builds on the same function, the old node is replaced by the newest. Users can also see the final image  path next to the build name after it has been completed successfully. 
I think it would be cool to have this for `run` and `deploy` actions as well. How do you think they should work? Is it better to have everything in the same place? So on the left you would see multiple rows each for a …

feat: add tool window for builds

---

build.gradle
src/main/java/com/redhat/devtools/intellij/knative/actions/func/BuildAction.java
src/main/java/com/redhat/devtools/intellij/knative/actions/func/DeployAction.java
src/main/java/com/redhat/devtools/intellij/knative/actions/func/RunAction.java
src/main/java/com/redhat/devtools/intellij/knative/actions/toolbar/ShowFunctionTaskHistoryAction.java
src/main/java/com/redhat/devtools/intellij/knative/actions/toolbar/StopFunctionTaskAction.java
src/main/java/com/redhat/devtools/intellij/knative/kn/Kn.java
src/main/java/com/redhat/devtools/intellij/knative/kn/KnCli.java
src/main/java/com/redhat/devtools/intellij/knative/tree/KnTreeStructure.java
src/main/java/com/redhat/devtools/intellij/knative/ui/buildRunDeployWindow/ActionFuncHandlerListener.java
src/main/java/com/redhat/devtools/intellij/knative/ui/buildRunDeployWindow/BuildRunDeployFuncPanel.java
src/main/java/com/redhat/devtools/intellij/knative/ui/buildRunDeployWindow/FuncActionNodeDescriptor.java
src/main/java/com/redhat/devtools/intellij/knative/ui/buildRunDeployWindow/FuncActionPipeline.java
src/main/java/com/redhat/devtools/intellij/knative/ui/buildRunDeployWindow/FuncActionPipelineBuilder.java
src/main/java/com/redhat/devtools/intellij/knative/ui/buildRunDeployWindow/FuncActionPipelineManager.java
src/main/java/com/redhat/devtools/intellij/knative/ui/buildRunDeployWindow/FuncActionTask.java
src/main/java/com/redhat/devtools/intellij/knative/ui/buildRunDeployWindow/IFuncAction.java
src/main/java/com/redhat/devtools/intellij/knative/ui/buildRunDeployWindow/IFuncActionPipeline.java
src/main/java/com/redhat/devtools/intellij/knative/ui/buildRunDeployWindow/buildFuncWindowTab/BuildFuncActionPipeline.java
src/main/java/com/redhat/devtools/intellij/knative/ui/buildRunDeployWindow/buildFuncWindowTab/BuildFuncActionTask.java
src/main/java/com/redhat/devtools/intellij/knative/ui/buildRunDeployWindow/buildFuncWindowTab/BuildFuncPanel.java
src/main/java/com/redhat/devtools/intellij/knative/ui/buildRunDeployWindow/runFuncWindowTab/RunFuncActionPipeline.java
src/main/java/com/redhat/devtools/intellij/knative/ui/buildRunDeployWindow/runFuncWindowTab/RunFuncPanel.java
src/main/java/com/redhat/devtools/intellij/knative/ui/toolwindow/BuildRunDeployWindowToolFactory.java
src/test/java/com/redhat/devtools/intellij/knative/actions/ActionTest.java
src/test/java/com/redhat/devtools/intellij/knative/actions/BuildActionTest.java
src/test/java/com/redhat/devtools/intellij/knative/actions/RunActionTest.java
src/test/java/com/redhat/devtools/intellij/knative/kn/KnCliTest.java

it resolves #174 
This patch adds 
- the stop action which allow to stop the execution of one task by clicking the button instead of killing the process from the terminal
- only one active run per function is allowed. So if a function is already running the user is informed and asked if he wants to stop the current executing process and start a new one

feat: add stop func task action and allow only one active run per func

---

build.gradle

it resolves #179 
This needs to be merged before the next release as some actions do not work properly otherwise. Mainly those that leverage watches (e.g undeploy)

chore: bump knative-client to 5.12.2 (#179)

---

src/main/java/com/redhat/devtools/intellij/knative/actions/RefreshAction.java
src/test/java/com/redhat/devtools/intellij/knative/actions/RefreshActionTest.java

It resolves #171 . I wasn't able to replicate it but looking at the code this should prevent the NPE faced by Gunjan

fix: prevent NPE when refresh action is executed (#171)

---

src/main/java/com/redhat/devtools/intellij/knative/actions/func/RepositoryAction.java
src/main/java/com/redhat/devtools/intellij/knative/kn/Kn.java
src/main/java/com/redhat/devtools/intellij/knative/kn/KnCli.java
src/main/java/com/redhat/devtools/intellij/knative/ui/UIConstants.java
src/main/java/com/redhat/devtools/intellij/knative/ui/createFunc/CreateFunctionChooserStepUI.java
src/main/java/com/redhat/devtools/intellij/knative/ui/createFunc/FunctionBuilderUtils.java
src/main/java/com/redhat/devtools/intellij/knative/ui/repository/CreateRepositoryDialog.java
src/main/java/com/redhat/devtools/intellij/knative/ui/repository/Repository.java
src/main/java/com/redhat/devtools/intellij/knative/ui/repository/RepositoryDialog.java
src/main/java/com/redhat/devtools/intellij/knative/ui/repository/RepositoryModelEditor.java
src/main/java/com/redhat/devtools/intellij/knative/ui/repository/RepositoryUtils.java
src/main/resources/META-INF/plugin.xml
src/main/resources/func.json
src/test/java/com/redhat/devtools/intellij/knative/kn/KnCliTest.java

it resolves #97 
This patch adds complete support for repositories. Users can add/remove/rename repos from the wizard.
Once a new repo has been added, new templates can be seen when creating a new function.

feat: add actions to manage Function repos (#97)

---

build.gradle
src/main/java/com/redhat/devtools/intellij/knative/Constants.java
src/main/java/com/redhat/devtools/intellij/knative/actions/func/BuildAction.java
src/main/java/com/redhat/devtools/intellij/knative/actions/func/DeployAction.java
src/main/java/com/redhat/devtools/intellij/knative/actions/func/OnClusterBuildAction.java
src/main/java/com/redhat/devtools/intellij/knative/actions/toolbar/StopFunctionTaskAction.java
src/main/java/com/redhat/devtools/intellij/knative/kn/Kn.java
src/main/java/com/redhat/devtools/intellij/knative/kn/KnCli.java
src/main/java/com/redhat/devtools/intellij/knative/ui/BaseDialog.java
src/main/java/com/redhat/devtools/intellij/knative/ui/GitDialog.java
src/main/java/com/redhat/devtools/intellij/knative/ui/UIConstants.java
src/main/java/com/redhat/devtools/intellij/knative/ui/invokeFunc/InvokeDialog.java
src/main/java/com/redhat/devtools/intellij/knative/utils/FuncUtils.java
src/main/java/com/redhat/devtools/intellij/knative/utils/model/GitRepoModel.java
src/main/java/com/redhat/devtools/intellij/knative/utils/model/ImageRegistryModel.java
src/main/resources/META-INF/plugin.xml
src/main/resources/func.json
src/test/java/com/redhat/devtools/intellij/knative/actions/BuildActionTest.java
src/test/java/com/redhat/devtools/intellij/knative/actions/DeployActionTest.java
src/test/java/com/redhat/devtools/intellij/knative/actions/OnClusterBuildActionTest.java
src/test/java/com/redhat/devtools/intellij/knative/kn/KnCliTest.java
src/test/java/com/redhat/devtools/intellij/knative/utils/ImageRegistryModelTest.java

it resolves #200 
it needs https://github.com/redhat-developer/intellij-common/pull/165 to work
This extend the deploy action to be run with the `--remote` and `--git-url` flag and support the on-cluster build action.
The feature itself is still a bit unstable from my pov. It failed easily if the env is not set correctly.
What i do to setup it is: start a cluster with clusterBot, install the pipeline 1.8 and serverless operators, create a new project,  install the following tasks
```
REPO=https://raw.githubusercontent.com/openshift-knative/kn-plugin-func/serverless-1.25.0
oc apply -f ${REPO}/pipelines/resources/tekton/task/func-buildpacks/0.1/func-buildpacks.yaml
oc apply -f ${REPO}/pipelines/resources/tekton/task/func-s2i/0.1/func-s2i.yaml
oc apply -f …
```

feat: add support for on-cluster build (#200)

---

.github/workflows/ci.yml
.github/workflows/conventionalCheck.yml
.github/workflows/release.yml

Hi!
Following the [GH Action Security Hardening](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions) guide we should use the commit SHA instead of the `branch` or `tag` for any third-party untrusted action.
This PR was submitted by a script.

chore: Pin 3rd-party actions to SHA1

---

gradle.properties
src/main/java/com/redhat/devtools/intellij/knative/func/BuildFuncActionTask.java
src/main/java/com/redhat/devtools/intellij/knative/func/FuncActionPipelineBuilder.java
src/main/java/com/redhat/devtools/intellij/knative/func/FuncActionTask.java
src/main/java/com/redhat/devtools/intellij/knative/func/RunFuncActionTask.java
src/main/java/com/redhat/devtools/intellij/knative/settings/SettingsState.java
src/main/java/com/redhat/devtools/intellij/knative/tree/KnFunctionDescriptor.java
src/main/java/com/redhat/devtools/intellij/knative/tree/KnSinkDescriptor.java
src/main/java/com/redhat/devtools/intellij/knative/tree/KnTreeStructure.java
src/main/java/com/redhat/devtools/intellij/knative/ui/CreateServiceDialog.java

extract of plugin verifier message after publishing 1.3.5 : 
```
Knative & Serverless Functions By Red Hat 1.3.5.129 is binary incompatible with IntelliJ IDEA Ultimate IU-231.9392.1 due to the following problems
Method not found (11 problems)
Invocation of unresolved method PsiAwareTextEditorImpl.getEditor() (10 problems)
Method CreateServiceDialog.createLogPanel() contains an invokevirtual instruction referencing an unresolved method PsiAwareTextEditorImpl.getEditor(). This can lead to NoSuchMethodError exception at runtime.
The method might have been declared in the super classes or in the super interfaces:
TextEditorImpl
UserDataHolderBase
Disposable
FileEditor
NavigatableFileEditor
TextEditor
UserDataHolder
UserDataHolderEx
```
those errors were not reported by the `runPluginVerifier` …

fix: fix compatibility problems

---

.github/workflows/IJ.yml
build.gradle
gradle.properties
src/main/resources/META-INF/plugin.xml

https://github.com/redhat-developer/intellij-common/pull/219

chore(skip-release): bump sinceIdea to 2022.3

---

src/main/java/com/redhat/devtools/intellij/knative/func/FuncActionPipeline.java
src/main/java/com/redhat/devtools/intellij/knative/func/FuncActionTask.java
src/main/java/com/redhat/devtools/intellij/knative/func/RunFuncActionTask.java
src/main/java/com/redhat/devtools/intellij/knative/tree/KnTreeStructure.java
src/main/java/com/redhat/devtools/intellij/knative/ui/toolwindow/GettingStartedToolWindow.java

fix: corrected deprecated API (#254)

---

src/main/java/com/redhat/devtools/intellij/knative/ui/toolwindow/KnBaseWindowTool.java

we dont need the `PopupHandlerAdapter` any more since we moved >`IC-2022.1`

fix: removed PopupHandlerAdapter
