src/main/java/com/redhat/devtools/intellij/knative/tree/KnRootNode.java, src/main/java/com/redhat/devtools/intellij/knative/tree/KnTreeStructure.java
=> update tree when namespace changes (#8)

Jenkinsfile
=> chore: Add Jenkinsfile

src/main/java/com/redhat/devtools/intellij/knative/Constants.java, src/main/java/com/redhat/devtools/intellij/knative/WindowToolFactory.java, src/main/java/com/redhat/devtools/intellij/knative/actions/RefreshAction.java, src/main/resources/META-INF/plugin.xml
=> Add Refresh action and toolbar for knative tree

src/main/resources/kn.json
=> Update kn CLI to '0.21.0'

Jenkinsfile
=> chore: Fix Jenkinsfile to handle plugin zip file with spaces

.github/workflows/ci.yml
=> chore: Add CI workflow

src/main/java/com/redhat/devtools/intellij/knative/actions/OpenInBrowserAction.java, src/main/resources/META-INF/plugin.xml
=> add open in browser action (#11)

src/main/java/com/redhat/devtools/intellij/knative/actions/DeleteAction.java, src/main/java/com/redhat/devtools/intellij/knative/actions/KnAction.java, src/main/java/com/redhat/devtools/intellij/knative/kn/Kn.java, src/main/java/com/redhat/devtools/intellij/knative/kn/KnCli.java, src/main/java/com/redhat/devtools/intellij/knative/ui/DeleteDialog.java, src/main/java/com/redhat/devtools/intellij/knative/utils/TreeHelper.java, src/main/resources/META-INF/plugin.xml
it resolves #26 
Classic delete action for services/revision with multiple selection available
=> add delete action (#26)

src/main/java/com/redhat/devtools/intellij/knative/kn/KnCli.java, src/main/java/com/redhat/devtools/intellij/knative/tree/KnTreeStructure.java, src/main/java/com/redhat/devtools/intellij/knative/tree/MessageNode.java
it resolves #34 
Not really sure how to handle this. Not a big fan of this solution but i cannot think at anything better.
=> Handle kn's no resource found message

.github/workflows/IJ.yml, build.gradle, gradle.properties, src/main/java/com/redhat/devtools/intellij/knative/kubernetes/KnativeHighlightInfoFilter.java, src/main/resources/META-INF/plugin-kubernetes.xml, src/main/resources/META-INF/plugin.xml
this resolves #45 
it works with https://github.com/redhat-developer/intellij-common/pull/55
@evidolob to give you some context. This patch is to prevent this error from happening https://github.com/redhat-developer/intellij-tekton/issues/263
=> add jetbrains k8s filtering for knative serving (#45)

src/main/java/com/redhat/devtools/intellij/knative/actions/CreateServiceAction.java, src/main/java/com/redhat/devtools/intellij/knative/kn/ServiceDeserializer.java, src/main/java/com/redhat/devtools/intellij/knative/listener/KnSaveInEditorListener.java, src/main/java/com/redhat/devtools/intellij/knative/ui/CreateServiceDialog.java, src/main/java/com/redhat/devtools/intellij/knative/utils/KnHelper.java
it resolves #49 
Now it works as before. Merging the update/create action created a wrong behavior. Now errors are displayed correctly.
=> fix wrong behavior in create service action (#49)

README.md
=> docs: Add marketplace badges to README.md

.github/workflows/conventionalCheck.yml, .github/workflows/release.yml
=> Add  workflows to work with conventional commits (#37)

.github/workflows/IJ.yml, build.gradle
=> chore: Add 2021.1

src/main/resources/META-INF/plugin.xml
=> chore: add ids to actions and extension points (#62)

src/main/java/com/redhat/devtools/intellij/knative/Constants.java, src/main/java/com/redhat/devtools/intellij/knative/ui/CreateServiceDialog.java
it resolves #48 
It needs https://github.com/redhat-developer/intellij-common/pull/79 to work
=> fix: disable create service button if name and image are empty (#48)

.github/workflows/ci.yml, build.gradle, src/it/java/com/redhat/devtools/intellij/knative/BaseTest.java, src/it/java/com/redhat/devtools/intellij/knative/KnServiceTest.java, src/it/resources/service.yaml, src/main/java/com/redhat/devtools/intellij/knative/utils/KnHelper.java
=> chore: set up integration tests

src/main/java/com/redhat/devtools/intellij/knative/ui/CreateServiceDialog.java
=> fix: default focus is on name textbox in create service wizard (#72)

.github/workflows/IJ.yml, .github/workflows/ci.yml, .github/workflows/release.yml, build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties, src/it/java/com/redhat/devtools/intellij/knative/BaseTest.java, src/main/java/com/redhat/devtools/intellij/knative/ui/CreateServiceDialog.java
Signed-off-by: Luca Stocchi <lstocchi@redhat.com>
=> chore: update settings

Jenkinsfile
=> chore: Switch to IntelliJ Gradle plugin 1.x

src/main/java/com/redhat/devtools/intellij/knative/actions/OpenInBrowserAction.java, src/main/java/com/redhat/devtools/intellij/knative/kn/KnCli.java, src/main/resources/META-INF/plugin.xml
=> feat: add open in browser action for functions (#94)

src/main/java/com/redhat/devtools/intellij/knative/actions/func/AddEnvAction.java, src/main/java/com/redhat/devtools/intellij/knative/actions/func/DeployAction.java, src/main/java/com/redhat/devtools/intellij/knative/actions/func/RemoveEnvAction.java, src/main/java/com/redhat/devtools/intellij/knative/kn/Kn.java, src/main/java/com/redhat/devtools/intellij/knative/kn/KnCli.java, src/main/java/com/redhat/devtools/intellij/knative/utils/FuncUtils.java, src/main/resources/META-INF/plugin.xml, src/test/java/com/redhat/devtools/intellij/knative/actions/AddEnvActionTest.java, src/test/java/com/redhat/devtools/intellij/knative/actions/RemoveEnvActionTest.java, src/test/java/com/redhat/devtools/intellij/knative/listener/KnSaveInEditorListenerTest.java
First part of #91 
Allows to add/remove envs to a function
=> feat: action for adding/removing envs for function (#91)

src/main/java/com/redhat/devtools/intellij/knative/actions/func/AddConfigAction.java, src/main/java/com/redhat/devtools/intellij/knative/actions/func/AddVolumeAction.java, src/main/java/com/redhat/devtools/intellij/knative/actions/func/RemoveConfigAction.java, src/main/java/com/redhat/devtools/intellij/knative/actions/func/RemoveEnvAction.java, src/main/java/com/redhat/devtools/intellij/knative/actions/func/RemoveVolumeAction.java, src/main/java/com/redhat/devtools/intellij/knative/kn/Kn.java, src/main/java/com/redhat/devtools/intellij/knative/kn/KnCli.java, src/main/resources/META-INF/plugin.xml, src/test/java/com/redhat/devtools/intellij/knative/actions/AddConfigActionTest.java, src/test/java/com/redhat/devtools/intellij/knative/actions/AddVolumeActionTest.java, src/test/java/com/redhat/devtools/intellij/knative/actions/RemoveConfigActionTest.java, src/test/java/com/redhat/devtools/intellij/knative/actions/RemoveEnvActionTest.java, src/test/java/com/redhat/devtools/intellij/knative/actions/RemoveVolumeActionTest.java
This is the second part of #91 
It adds actions to work with volumes.
I reorganized the actions based on discussion with Mohit, now it looks like
=> feat: add action to configure volumes on function (#91)

src/main/java/com/redhat/devtools/intellij/knative/actions/RefreshAction.java
=> fix: fix class cast exception when refreshing root node

src/main/java/com/redhat/devtools/intellij/knative/ui/createFunc/CreateFunctionChooserStep.java, src/main/java/com/redhat/devtools/intellij/knative/ui/createFunc/CreateFunctionChooserStepUI.java, src/main/java/com/redhat/devtools/intellij/knative/ui/createFunc/FunctionBuilderUtils.java, src/main/java/com/redhat/devtools/intellij/knative/ui/createFunc/FunctionModuleBuilder.java, src/main/java/com/redhat/devtools/intellij/knative/ui/createFunc/FunctionProjectBuilder.java, src/main/java/com/redhat/devtools/intellij/knative/ui/toolwindow/FunctionsWindowToolFactory.java, src/main/java/com/redhat/devtools/intellij/knative/ui/toolwindow/WindowToolFactory.java, src/main/resources/META-INF/plugin.xml
=> fix: enable creation of function project in IDE different from IDEA

src/main/resources/kn.json
=> chore: bump kn cli to 1.2.0 (#108)

build.gradle, src/main/java/com/redhat/devtools/intellij/knative/kn/KnCli.java, src/main/resources/func.json, src/main/resources/kn.json
=> feat: bump common lib and enable silentMode

src/main/java/com/redhat/devtools/intellij/knative/kn/KnCli.java, src/test/java/com/redhat/devtools/intellij/knative/kn/KnCliTest.java
=> fix: pass envs when executing commands on terminal (#136)

src/main/resources/kn.json
it resolves #134 
It needs https://github.com/redhat-developer/intellij-common/pull/137
=> feat: bump kn cli + add arm64 version for Mac

src/main/resources/func.json
=> chore: bump func cli to 0.23 (#143)

src/main/resources/func.json
=> chore: bump func cli to 0.23.1

src/main/java/com/redhat/devtools/intellij/knative/actions/func/InvokeAction.java, src/main/java/com/redhat/devtools/intellij/knative/kn/Kn.java, src/main/java/com/redhat/devtools/intellij/knative/kn/KnCli.java, src/test/java/com/redhat/devtools/intellij/knative/kn/KnCliTest.java
=> fix: prevent opening new tab when invoking function and show notification (#141)

src/main/java/com/redhat/devtools/intellij/knative/kn/KnCli.java
=> fix: add empty registry flag as a workaround for bug on func cli with ocp cluster

build.gradle
=> chore: bump kubernetes client to 5.7.4 (#123)

src/main/resources/kn.json
=> chore: bump kn cli to 1.4.0 (#158)

src/main/java/com/redhat/devtools/intellij/knative/ui/createFunc/FunctionModuleBuilder.java
=> fix: show new function module when created with wizard (#168)

src/main/java/com/redhat/devtools/intellij/knative/Constants.java, src/main/java/com/redhat/devtools/intellij/knative/actions/func/BuildAction.java, src/main/java/com/redhat/devtools/intellij/knative/actions/func/DeployAction.java, src/main/java/com/redhat/devtools/intellij/knative/kn/Kn.java, src/main/java/com/redhat/devtools/intellij/knative/kn/KnCli.java, src/main/java/com/redhat/devtools/intellij/knative/ui/buildRunDeployWindow/BuildRunDeployFuncPanel.java, src/main/java/com/redhat/devtools/intellij/knative/ui/buildRunDeployWindow/FuncActionPipeline.java, src/main/java/com/redhat/devtools/intellij/knative/ui/buildRunDeployWindow/FuncActionPipelineBuilder.java, src/main/java/com/redhat/devtools/intellij/knative/ui/buildRunDeployWindow/FuncActionTask.java, src/main/java/com/redhat/devtools/intellij/knative/ui/buildRunDeployWindow/buildFuncWindowTab/BuildFuncActionPipeline.java, src/main/java/com/redhat/devtools/intellij/knative/ui/buildRunDeployWindow/deployFuncWindowTab/DeployFuncActionPipeline.java, src/main/java/com/redhat/devtools/intellij/knative/ui/buildRunDeployWindow/deployFuncWindowTab/DeployFuncPanel.java, src/main/java/com/redhat/devtools/intellij/knative/ui/buildRunDeployWindow/runFuncWindowTab/RunFuncPanel.java, src/main/java/com/redhat/devtools/intellij/knative/ui/toolwindow/BuildRunDeployWindowToolFactory.java, src/test/java/com/redhat/devtools/intellij/knative/actions/ActionTest.java, src/test/java/com/redhat/devtools/intellij/knative/actions/DeployActionTest.java, src/test/java/com/redhat/devtools/intellij/knative/kn/KnCliTest.java
=> feat: add deploy tab in function tool window (#167)

src/main/resources/kn.json
=> chore: bump kn cli to 1.5.0 (#185)

src/main/resources/func.json
=> chore: bump func cli to 0.24.0 (#184)

build.gradle
=> chore: bump telemetry to 0.0.3.33 (#189)

src/main/java/com/redhat/devtools/intellij/knative/actions/func/BuildAction.java, src/main/java/com/redhat/devtools/intellij/knative/actions/func/DeployAction.java
=> fix: ask image name only once when deploying new func (#191)

src/main/java/com/redhat/devtools/intellij/knative/actions/func/InvokeAction.java, src/main/java/com/redhat/devtools/intellij/knative/actions/func/RunAction.java, src/main/java/com/redhat/devtools/intellij/knative/ui/buildRunDeployWindow/FuncActionPipelineBuilder.java, src/main/java/com/redhat/devtools/intellij/knative/ui/buildRunDeployWindow/FuncActionTask.java, src/main/java/com/redhat/devtools/intellij/knative/ui/buildRunDeployWindow/runFuncWindowTab/RunFuncActionTask.java
=> feat: inform user func is not running when invoking a non-running func (#127)

src/main/resources/META-INF/plugin.xml
=> chore: update CRC link (#202)

src/main/resources/META-INF/plugin.xml
it resolves #206 
We need to release a new version for common lib bump. So i'd add this in the release as well
=> chore: edit description content style in JB marketplace (#206)

build.gradle
=> chore: bump common to 1.7.1 (#203)

gradle.properties, src/main/resources/META-INF/plugin.xml
=> chore(skip-release): Prepare for 1.2.1

.github/workflows/IJ.yml, build.gradle
=> build: Add IntelliJ 2022.2

src/main/resources/kn.json
=> chore: bump kn cli to 1.7.0 (#213)

src/main/java/com/redhat/devtools/intellij/knative/actions/func/RemoveEnvAction.java, src/main/java/com/redhat/devtools/intellij/knative/actions/func/RemoveVolumeAction.java, src/main/java/com/redhat/devtools/intellij/knative/tree/KnFunctionsTreeStructure.java, src/main/resources/func.json, src/test/java/com/redhat/devtools/intellij/knative/actions/RemoveEnvActionTest.java, src/test/java/com/redhat/devtools/intellij/knative/actions/RemoveVolumeActionTest.java
it resolves #215 
The structure of the func.yaml changed with this release. Had to fix some fields path.
Tested the rest and seems working fine.
=> chore: bump func cli to 1.8.0 (#215)

src/main/java/com/redhat/devtools/intellij/knative/actions/func/OnClusterBuildAction.java, src/main/java/com/redhat/devtools/intellij/knative/git/GitHandler.java, src/main/java/com/redhat/devtools/intellij/knative/ui/GitDialog.java, src/main/resources/META-INF/plugin-github.xml, src/main/resources/META-INF/plugin.xml
=> fix: add config-file for github plugin (#218)

build.gradle
=> chore: bumped openshift-client to 5.12.4 (#221)

src/main/java/com/redhat/devtools/intellij/knative/ui/toolwindow/FunctionsWindowToolFactory.java, src/main/java/com/redhat/devtools/intellij/knative/ui/toolwindow/KnBaseWindowTool.java, src/main/java/com/redhat/devtools/intellij/knative/ui/toolwindow/WindowToolFactory.java
=> chore: rm'd reflective buildModel & replaced project by content as disposable (223#)

build.gradle, gradle.properties, src/main/resources/META-INF/plugin.xml
=> chore(skip-release): prepare for 1.3.2 (#227)

README.md
Signed-off-by: Mohit Suman <mohit.skn@gmail.com>
=> chore: update readme badge and description

gradle.properties
Signed-off-by: Luca Stocchi <lstocchi@redhat.com>
=> chore(skip-release): bump to 1.4.0-SNAPSHOT

src/main/resources/func.json, src/main/resources/kn.json
=> chore: update kn cli to 1.8.1 and func clic to 1.8.2 (#236)

build.gradle, src/main/java/com/redhat/devtools/intellij/knative/kn/Kn.java, src/main/java/com/redhat/devtools/intellij/knative/kn/KnCli.java, src/main/java/com/redhat/devtools/intellij/knative/utils/KnHelper.java, src/test/java/com/redhat/devtools/intellij/knative/utils/KnHelperTest.java
depends on https://github.com/redhat-developer/intellij-kubernetes/pull/548, https://github.com/redhat-developer/intellij-common/pull/173
fixes #233
=> chore: bump kubernetes-client 6.4.0 (#233)

src/main/resources/kn.json
related to https://github.com/redhat-developer/intellij-openshift-connector/issues/656, https://github.com/redhat-developer/intellij-openshift-connector/issues/653
=> fix: corrected apple silicon architecture id -> dl correct binary

gradle.properties, src/main/resources/META-INF/plugin.xml
=> chore(skip-release): prepare 1.3.8
